config/routes.rb
Rails.application.routes.draw do

	post 'auth/logout', as: 'logout'
  match 'auth/login', as: 'login', via: [:get, :post]
  match 'auth/register', as: 'register', via: [:get, :post]
  resources :transactions
  post 'accounts/:id/operation', to: 'accounts#operation', as: 'accounts_operation'
  get 'users/accounts', to: 'users#accounts'
  root 'main#index', as: 'main_index'
  resources :accounts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account

  validates :type_id, :amount, :desc, presence: true
  validates :amount, numericality: { only_integer: true}
  validates :type_id, inclusion: { in: [AccountService::TYPE_WRITE_OFF, AccountService::TYPE_TOP_UP],
  		message: 'type not permitted'}

  def getType
  	return 'Write Off' if type_id == AccountService::TYPE_WRITE_OFF
  	'Top Up'
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :accounts
	has_many :transactions, through: :accounts
	has_secure_password

	validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :operation]


  def initialize
    super
    @account_service = AccountService.new
  end

  def operation
    @errors = []
    data = params.permit(:amount, :desc, :button)

    transactionParams = {
      type: data[:button],
      amount: data[:amount],
      desc: data[:desc],
    }
    
    @result_balance = @account.balance
    
    suppress(ErrorBag::ValidationException) do
      @result_balance = @account_service.operation(@account, transactionParams)
    end

    @accountTransactions = @account.transactions

  
    respond_to do |format|
      format.js
    end


  end

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = @logged_user.accounts
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @accountTransactions = @account.transactions
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = @account_service.create(@logged_user)

    redirect_to accounts_path
  end


  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include LoggedUser

	rescue_from Exception, with: :on_exception
	before_action :getLoggedUser, except: [:login, :register]

	def initialize
		super
		@auth_service = AuthService.new
		ErrorBag.clear
	end

  def on_exception(exception)
    NotificationMailer.error(exception.message, exception.backtrace).deliver_later
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  	login_params = allowed_params
  	@url = login_path

  	suppress(ErrorBag::ValidationException) do
  		if request.post? and login_params.permitted?
	  		user = @auth_service.login(
	  			login_params[:name],
	  			login_params[:password]
	  		)		

	  		session[:logged_user_id] = user.id
  			redirect_to accounts_path
  		end
  	end
  end

  def register
  	reg_params = allowed_params
  	@url = register_path
  	
  	if request.post? and reg_params.permitted?
  		suppress(ErrorBag::ValidationException) do
  			user = @auth_service.register(reg_params)
        account_service = AccountService.new
        account_service.create(user)
        redirect_to login_path
  		end
  	end
  end

  def logout
  	session[:logged_user_id] = nil
  	redirect_to login_path
  end

  private
  	def allowed_params
  		params.permit(:name, :password)
  	end
end

app/controllers/concerns/logged_user.rb
module LoggedUser
	def getLoggedUser
		unless session[:logged_user_id]
			redirect_to login_path
			return
		end
		@logged_user = User.find_by(id: session[:logged_user_id])

		unless @logged_user
		 	redirect_to login_path
		end 
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = @logged_user.transactions.includes(:account)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/_transactions.html.erb
<% if @accountTransactions.count > 0 %>
<h3>Transactions</h3>
<table class="blueTable">
  <thead>
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Description</th>
      <th>Created</th>
    </tr>
  </thead>

  <tbody>
    <% @accountTransactions.each do |transaction| %>
      <tr>
        <td><%= transaction.getType %></td>
        <td><%= transaction.amount.abs %> $</td>
        <td><%= transaction.desc %></td>
        <td><%= transaction.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class="blueTable">
  <thead>
    <tr>
      <th>Id</th>
      <th>Balance</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to "Account ##{account.id}", account %></td>
        <td><%= account.balance %> $</td>
        <td><%= account.created_at %></td>
        <td><%= account.updated_at %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Create new Account', accounts_path, data: {confirm: 'Are you sure?'} %>

app/views/accounts/operation.js.erb
$('.errors').html("<%=j render('layouts/errors') %>")
$('.transactions').html("<%=j render('transactions') %>")
$('.account-balance-js').text('<%= @result_balance %>')

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
	<p>
	  <strong>Balance:</strong>
	  <span class="account-balance-js">
	  	<%= @account.balance %>
	  </span>

	  <br>
	  <div class="errors"></div>
	  <%= form_with url: accounts_operation_path, remote: true do %>
	  	<%= label_tag(:amount, 'Amount') %>
	  	<%= number_field_tag(:amount) %>
	  	<%= label_tag(:desc, 'Description') %>
	  	<%= text_area_tag(:desc) %>
	  	<br>
	  	<br>
	  	<%= button_tag(class: 'btn btn-danger', value: AccountService::TYPE_WRITE_OFF) do %>
	  		<i class="glyphicon glyphicon-minus"></i> Write Off
	  	<% end %>
	  	<%= button_tag(class: 'btn btn-primary', value: AccountService::TYPE_TOP_UP) do %>
	  		<i class="glyphicon glyphicon-plus"></i> Top Up
	  	<% end %>
	  <% end %>
	</p>
	<div class="transactions">
		<%= render 'transactions' %>
	</div>
</div>

app/views/layouts/_errors.html.erb
<ul>
	<% ErrorBag.getErrors.each do |error| %>
	  <li><%= error %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body role="document">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bank</a>
        </div>
        <div class="navbar-collapse collapse">
          <% if @logged_user %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Logout (#{@logged_user.name})" , logout_path, method: :post %></li>
            <li><%= link_to 'Accounts' , accounts_path %></li>
            <li><%= link_to 'Transcations' , transactions_path %></li>
          </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container theme-showcase" role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table class="blueTable">
  <thead>
    <tr>
      <th>Type</th>
      <th>Account</th>
      <th>Amount</th>
      <th>Description</th>
      <th>Created</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.getType %></td>
        <td><%= "Account ##{transaction.account.id}" %></td>
        <td><%= transaction.amount.abs %></td>
        <td><%= transaction.desc %></td>
        <td><%= transaction.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>